export const FILENAME_CACHE_KEY = 'dj:filename'
export const CONTENT_CACHE_KEY = 'dj:content'
export const MENU_OPEN_CACHE_KEY = 'dj:settings-menu-open'
export const CONTENT_LAST_SAVE_CACHE_KEY = 'dj:content-last-save'
export const CONTENT_LAST_SAVE_DATETIME_CACHE_KEY = 'dj:content-last-save-dt'
